# Generated by Django 5.0.14 on 2026-05-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, help_text='Node asal terjadinya anomali', max_length=50)),
                ('timestamp', models.DateTimeField(help_text='Waktu pembacaan sensor saat terdeteksi anomali')),
                ('metric', models.CharField(help_text='Metrik yang bermasalah (contoh: temperature, vibration, gas_level)', max_length=50)),
                ('value', models.FloatField(help_text='Nilai sensor aktual yang terbaca')),
                ('threshold', models.FloatField(help_text='Nilai batas aman (threshold) yang dilanggar')),
                ('message', models.TextField(help_text='Deskripsi atau pesan peringatan terkait anomali')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu pencatatan log anomali')),
            ],
            options={
                'verbose_name': 'Anomaly Log',
                'verbose_name_plural': 'Anomaly Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, help_text='ID unik node pengirim (contoh: node_1, node_2)', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Waktu pembacaan sensor dari node')),
                ('temperature', models.FloatField(blank=True, help_text='Suhu Mesin / Suhu Lingkungan (°C)', null=True)),
                ('vibration', models.FloatField(blank=True, help_text='Nilai getaran dari MPU6050 (g / m/s²)', null=True)),
                ('current', models.FloatField(blank=True, help_text='Konsumsi arus listrik dari PZEM004T (Ampere)', null=True)),
                ('voltage', models.FloatField(blank=True, help_text='Tegangan listrik dari PZEM004T (Volt)', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Kelembaban udara dari DHT22 (%)', null=True)),
                ('gas_level', models.FloatField(blank=True, help_text='Kadar gas/asap dari MQ-2 (ppm)', null=True)),
                ('raw_payload', models.JSONField(blank=True, help_text='Payload JSON asli dari MQTT', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu data disimpan ke database backend')),
            ],
            options={
                'verbose_name': 'Telemetry Data',
                'verbose_name_plural': 'Telemetry Data Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
