# Generated by Django 5.0.14 on 2026-05-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(db_index=True, help_text='Nama metrik sensor (contoh: temperature, vibration, gas_level)', max_length=50, unique=True)),
                ('value', models.FloatField(help_text='Nilai batas aman sensor')),
                ('label', models.CharField(help_text='Label tampilan sensor (contoh: Batas Suhu Maksimum)', max_length=100)),
                ('unit', models.CharField(blank=True, default='', help_text='Satuan sensor (contoh: °C, g, ppm)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Deskripsi fungsi batas aman', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sensor Threshold',
                'verbose_name_plural': 'Sensor Thresholds',
            },
        ),
    ]
